export const QUIZES_FETCH = {
  START: `QUIZES_FETCH_START`,
  SUCCESS: `QUIZES_FETCH_SUCCESS`,
  ERROR: `QUIZES_FETCH_ERROR`,
};

export const QUIZ = {
  FETCH_SUCCESS: 'QUIZ_FETCH_SUCCESS',
  RESTART: `QUIZ_RESTART`,
  SET_STATE: `QUIZ_SET_STATE`,
  FINISHED: `QUIZ_FINISHED`,
  CURRENT_QUESTION: `QUIZ_CURRENT_QUESTION`,
};

export const CREATE_QUESTION = `CREATE_QUESTION`;
export const ADD_QUIZ = `ADD_QUIZ`;